import type { ThemeDocument } from "./schema";
import { THEME_FILE_KIND, THEME_SCHEMA_VERSION } from "../../app/brand";
import { duskTheme, mistTheme } from "./presets";

export { duskTheme, mistTheme } from "./presets";

type Palette = {
  id: string;
  name: string;
  description: string;
  base: "light" | "dark";
  tags: string[];
  appBackground: string;
  raisedBackground: string;
  primaryText: string;
  secondaryText: string;
  mutedText: string;
  accent: string;
  accentHover: string;
  accentText: string;
};

const sharedAppearance = {
  fontFamily: '"DM Sans Variable", "Segoe UI", sans-serif',
  headingFontFamily: '"Fraunces Variable", Georgia, serif',
  baseFontSize: 14,
  fontWeight: 450,
  headingWeight: 560,
  letterSpacing: "0.01em",
  lineHeight: 1.45,
  cornerRadiusSmall: 8,
  cornerRadiusMedium: 14,
  cornerRadiusLarge: 22,
  buttonRadius: 999,
  artworkRadius: 16,
  borderWidth: 1,
  shadowStrength: 0.4,
  blurStrength: 18,
  surfaceOpacity: 0.72,
  spacingScale: 1,
  controlHeight: 36,
  sidebarWidth: 72,
  inspectorWidth: 320,
} as const;

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const raw = hex.replace("#", "").trim();
  const full =
    raw.length === 3
      ? raw
          .split("")
          .map((c) => `${c}${c}`)
          .join("")
      : raw;
  const n = Number.parseInt(full, 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

function rgba(hex: string, alpha: number): string {
  const { r, g, b } = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

/** Stable background variety — not every preset is a gradient wash. */
function pickBackgroundMode(
  p: Palette,
): "solid" | "gradient" | "none" {
  const tags = new Set(p.tags);
  if (tags.has("neon")) return "gradient";
  if (tags.has("mono") || tags.has("paper")) return "solid";
  const hash = [...p.id].reduce((sum, ch) => sum + ch.charCodeAt(0), 0);
  const modes = ["solid", "gradient", "none", "solid", "gradient"] as const;
  return modes[hash % modes.length] ?? "solid";
}

function fromPalette(p: Palette): ThemeDocument {
  const dark = p.base === "dark";
  const mode = pickBackgroundMode(p);
  const ink = dark ? "#ffffff" : p.primaryText;
  const panel = p.raisedBackground;

  return {
    kind: THEME_FILE_KIND,
    schemaVersion: THEME_SCHEMA_VERSION,
    id: p.id,
    name: p.name,
    description: p.description,
    base: p.base,
    tags: p.tags,
    colors: {
      appBackground: p.appBackground,
      raisedBackground: p.raisedBackground,
      // Tint panels from the theme (Monkeytype-style), not generic white glass.
      surface: rgba(panel, dark ? 0.72 : 0.88),
      surfaceHover: rgba(panel, dark ? 0.88 : 0.96),
      surfaceActive: rgba(p.accent, dark ? 0.22 : 0.16),
      surfaceSelected: rgba(p.accent, dark ? 0.28 : 0.2),
      primaryText: p.primaryText,
      secondaryText: p.secondaryText,
      mutedText: p.mutedText,
      accent: p.accent,
      accentHover: p.accentHover,
      accentText: p.accentText,
      secondaryAccent: p.accentHover,
      border: rgba(ink, dark ? 0.1 : 0.1),
      divider: rgba(ink, dark ? 0.07 : 0.08),
      focusRing: p.accent,
      success: "#3f9d78",
      warning: "#d08a4c",
      danger: "#d16a6a",
      artworkGlow: rgba(p.accent, dark ? 0.28 : 0.18),
      waveform: p.accent,
      progressTrack: rgba(ink, dark ? 0.16 : 0.14),
      progressFill: p.accent,
      lyricActive: p.primaryText,
      lyricPast: rgba(p.primaryText, dark ? 0.42 : 0.4),
      lyricFuture: rgba(p.primaryText, dark ? 0.72 : 0.68),
      selection: rgba(p.accent, dark ? 0.28 : 0.18),
      scrollbar: rgba(ink, dark ? 0.24 : 0.22),
      tooltipBackground: dark ? p.raisedBackground : p.primaryText,
      tooltipText: dark ? p.primaryText : p.appBackground,
      contextMenuBackground: p.raisedBackground,
    },
    appearance: {
      ...sharedAppearance,
      shadowStrength: dark ? 0.55 : 0.28,
      blurStrength: mode === "solid" || mode === "none" ? (dark ? 12 : 10) : dark ? 22 : 18,
      surfaceOpacity: mode === "solid" || mode === "none" ? 0.92 : 0.72,
    },
    background: {
      mode,
      blur: 0,
      darkness: mode === "gradient" ? (dark ? 0.18 : 0.03) : 0,
      brightness: 1,
      saturation: mode === "gradient" ? 1.05 : 1,
      overlayOpacity:
        mode === "none" ? 0 : mode === "solid" ? (dark ? 0.08 : 0.02) : dark ? 0.22 : 0.08,
      noiseAmount: mode === "none" ? 0 : mode === "solid" ? 0.02 : 0.04,
      vignetteAmount:
        mode === "none" ? 0 : mode === "solid" ? (dark ? 0.12 : 0.04) : dark ? 0.3 : 0.12,
      animationStrength: mode === "gradient" ? 0.2 : 0,
    },
  };
}

/** Original Atrium palettes — not third-party theme packs. */
const paletteCatalog: Palette[] = [
  {
    id: "atrium-ink-amber",
    name: "Ink Amber",
    description: "dark charcoal with gold",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#191815",
    raisedBackground: "#23211c",
    primaryText: "#efe7d7",
    secondaryText: "#c8bba4",
    mutedText: "#8f8574",
    accent: "#e2b714",
    accentHover: "#f0c62a",
    accentText: "#1a1608",
  },
  {
    id: "atrium-nordic-night",
    name: "Nordic Night",
    description: "cool arctic dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#1b222a",
    raisedBackground: "#242d38",
    primaryText: "#e6edf5",
    secondaryText: "#b7c4d4",
    mutedText: "#8392a6",
    accent: "#88c0d0",
    accentHover: "#9fd0dd",
    accentText: "#132029",
  },
  {
    id: "atrium-violet-room",
    name: "Violet Room",
    description: "plum night lilac",
    base: "dark",
    tags: ["dark","violet"],
    appBackground: "#1a1522",
    raisedBackground: "#251f30",
    primaryText: "#f0e8fb",
    secondaryText: "#c7b8db",
    mutedText: "#8f819f",
    accent: "#b794f4",
    accentHover: "#c9a9f8",
    accentText: "#1b1228",
  },
  {
    id: "atrium-matrix-leaf",
    name: "Matrix Leaf",
    description: "terminal green",
    base: "dark",
    tags: ["dark","green"],
    appBackground: "#0b120c",
    raisedBackground: "#121a13",
    primaryText: "#d7f7d9",
    secondaryText: "#9dcf9f",
    mutedText: "#6a916c",
    accent: "#39d353",
    accentHover: "#58e06e",
    accentText: "#041008",
  },
  {
    id: "atrium-crimson-stage",
    name: "Crimson Stage",
    description: "deep stage reds",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#180e10",
    raisedBackground: "#241418",
    primaryText: "#f7e8ea",
    secondaryText: "#d4b0b6",
    mutedText: "#9a7278",
    accent: "#e2556c",
    accentHover: "#ef6d81",
    accentText: "#1a080c",
  },
  {
    id: "atrium-ocean-glass",
    name: "Ocean Glass",
    description: "teal over deep blue",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0f1a22",
    raisedBackground: "#172632",
    primaryText: "#e5f3fb",
    secondaryText: "#a9c7d8",
    mutedText: "#7392a4",
    accent: "#3db8a8",
    accentHover: "#55c9ba",
    accentText: "#06201c",
  },
  {
    id: "atrium-sunset-lane",
    name: "Sunset Lane",
    description: "coral dusk",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#1c1214",
    raisedBackground: "#2a1a1d",
    primaryText: "#ffe8df",
    secondaryText: "#e0b8ab",
    mutedText: "#a88278",
    accent: "#ff7a59",
    accentHover: "#ff9175",
    accentText: "#2a100c",
  },
  {
    id: "atrium-graphite",
    name: "Graphite",
    description: "neutral studio charcoal",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#17181a",
    raisedBackground: "#222326",
    primaryText: "#eceef1",
    secondaryText: "#b5b9c0",
    mutedText: "#858991",
    accent: "#7aa2ff",
    accentHover: "#93b3ff",
    accentText: "#0f1420",
  },
  {
    id: "atrium-midnight-jazz",
    name: "Midnight Jazz",
    description: "indigo club",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#111526",
    raisedBackground: "#1a2036",
    primaryText: "#e8ecff",
    secondaryText: "#b4bce0",
    mutedText: "#8088ad",
    accent: "#6c8cff",
    accentHover: "#87a1ff",
    accentText: "#10162a",
  },
  {
    id: "atrium-copper-wire",
    name: "Copper Wire",
    description: "industrial copper",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#171210",
    raisedBackground: "#241b17",
    primaryText: "#f2e6dc",
    secondaryText: "#cdb4a4",
    mutedText: "#947c6e",
    accent: "#c57b4a",
    accentHover: "#d58c5c",
    accentText: "#1c100a",
  },
  {
    id: "atrium-peach-dawn",
    name: "Peach Dawn",
    description: "soft peach daylight",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f7eee7",
    raisedBackground: "#fff8f3",
    primaryText: "#3a2a24",
    secondaryText: "#6b534a",
    mutedText: "#927870",
    accent: "#e07a5f",
    accentHover: "#c9654c",
    accentText: "#fff8f3",
  },
  {
    id: "atrium-lilac-mist",
    name: "Lilac Mist",
    description: "lavender morning",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#efeaf6",
    raisedBackground: "#f8f5fc",
    primaryText: "#2c2438",
    secondaryText: "#5c526e",
    mutedText: "#857995",
    accent: "#8b6cc7",
    accentHover: "#7356b0",
    accentText: "#f8f5fc",
  },
  {
    id: "atrium-paper-ink",
    name: "Paper Ink",
    description: "high-contrast reading",
    base: "light",
    tags: ["light","mono"],
    appBackground: "#f2f0ea",
    raisedBackground: "#fcfbf7",
    primaryText: "#1c1b19",
    secondaryText: "#4a4742",
    mutedText: "#7a756c",
    accent: "#2f6fed",
    accentHover: "#1f5ad0",
    accentText: "#ffffff",
  },
  {
    id: "atrium-matcha",
    name: "Matcha",
    description: "green tea lounge",
    base: "light",
    tags: ["light","green"],
    appBackground: "#eaf1e6",
    raisedBackground: "#f5faf2",
    primaryText: "#243028",
    secondaryText: "#4c5d52",
    mutedText: "#748579",
    accent: "#5a8f63",
    accentHover: "#487552",
    accentText: "#f5faf2",
  },
  {
    id: "atrium-honeycomb",
    name: "Honeycomb",
    description: "honey over cream",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f6efd9",
    raisedBackground: "#fff8e8",
    primaryText: "#3a2f14",
    secondaryText: "#6b5a2d",
    mutedText: "#94824d",
    accent: "#c98a1c",
    accentHover: "#a97212",
    accentText: "#fff8e8",
  },
  {
    id: "atrium-sakura",
    name: "Sakura",
    description: "soft pink blossom",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f8eef2",
    raisedBackground: "#fff7fa",
    primaryText: "#3a2430",
    secondaryText: "#6d4a59",
    mutedText: "#977484",
    accent: "#d66d95",
    accentHover: "#bf5780",
    accentText: "#fff7fa",
  },
  {
    id: "atrium-ember-forge",
    name: "Ember Forge",
    description: "molten orange night",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#1a100c",
    raisedBackground: "#271812",
    primaryText: "#ffe8d6",
    secondaryText: "#d9b39a",
    mutedText: "#9e7a66",
    accent: "#ff8a3d",
    accentHover: "#ff9f5c",
    accentText: "#2a1208",
  },
  {
    id: "atrium-glacier",
    name: "Glacier",
    description: "icy pale blue light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e8f1f6",
    raisedBackground: "#f5fafc",
    primaryText: "#1e2c36",
    secondaryText: "#4a5f6c",
    mutedText: "#7a8f9c",
    accent: "#3a8fb7",
    accentHover: "#2d7394",
    accentText: "#f5fafc",
  },
  {
    id: "atrium-nocturne",
    name: "Nocturne",
    description: "piano-black violet",
    base: "dark",
    tags: ["dark","violet"],
    appBackground: "#120f18",
    raisedBackground: "#1c1724",
    primaryText: "#ede6f8",
    secondaryText: "#bfb3d4",
    mutedText: "#85799a",
    accent: "#9b7bff",
    accentHover: "#b197ff",
    accentText: "#140e22",
  },
  {
    id: "atrium-citrus-grove",
    name: "Citrus Grove",
    description: "lime daylight",
    base: "light",
    tags: ["light","green"],
    appBackground: "#eef5e4",
    raisedBackground: "#f7fbeb",
    primaryText: "#27301c",
    secondaryText: "#51603c",
    mutedText: "#7e8d64",
    accent: "#7fad2f",
    accentHover: "#6a9224",
    accentText: "#f7fbeb",
  },
  {
    id: "atrium-rosewood",
    name: "Rosewood",
    description: "deep rose wood",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#1a1114",
    raisedBackground: "#26181c",
    primaryText: "#f6e6ea",
    secondaryText: "#d0b0b8",
    mutedText: "#967880",
    accent: "#d45d7a",
    accentHover: "#e2758e",
    accentText: "#220c14",
  },
  {
    id: "atrium-slate-blue",
    name: "Slate Blue",
    description: "muted steel office",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#15191f",
    raisedBackground: "#1f252e",
    primaryText: "#e4eaf2",
    secondaryText: "#aeb8c6",
    mutedText: "#7b8696",
    accent: "#5b8def",
    accentHover: "#749ff2",
    accentText: "#0e1626",
  },
  {
    id: "atrium-ivory-coast",
    name: "Ivory Coast",
    description: "warm ivory sand",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f4ecdf",
    raisedBackground: "#fbf6ee",
    primaryText: "#352b1e",
    secondaryText: "#64553f",
    mutedText: "#92816a",
    accent: "#b8833a",
    accentHover: "#9a6c2c",
    accentText: "#fbf6ee",
  },
  {
    id: "atrium-neon-alley",
    name: "Neon Alley",
    description: "magenta street night",
    base: "dark",
    tags: ["dark","neon"],
    appBackground: "#120816",
    raisedBackground: "#1d0f24",
    primaryText: "#f8e6ff",
    secondaryText: "#d0b0e0",
    mutedText: "#9578a8",
    accent: "#ff3db8",
    accentHover: "#ff63c8",
    accentText: "#240816",
  },
  {
    id: "atrium-pine-cabin",
    name: "Pine Cabin",
    description: "forest brown light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#e9ece4",
    raisedBackground: "#f4f6f0",
    primaryText: "#2a3024",
    secondaryText: "#535c48",
    mutedText: "#7d8672",
    accent: "#4f7a4a",
    accentHover: "#3f633c",
    accentText: "#f4f6f0",
  },
  {
    id: "atrium-cobalt-deep",
    name: "Cobalt Deep",
    description: "rich cobalt dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0d1424",
    raisedBackground: "#152038",
    primaryText: "#e2e9ff",
    secondaryText: "#aebae4",
    mutedText: "#7a86b0",
    accent: "#3d6bff",
    accentHover: "#5a84ff",
    accentText: "#0a1230",
  },
  {
    id: "atrium-buttercream",
    name: "Buttercream",
    description: "soft yellow cream",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f7f2de",
    raisedBackground: "#fcf8ec",
    primaryText: "#3a341c",
    secondaryText: "#675e3c",
    mutedText: "#948a64",
    accent: "#d4b03a",
    accentHover: "#b89424",
    accentText: "#fcf8ec",
  },
  {
    id: "atrium-ash-violet",
    name: "Ash Violet",
    description: "desaturated violet dark",
    base: "dark",
    tags: ["dark","violet"],
    appBackground: "#17151c",
    raisedBackground: "#221f2a",
    primaryText: "#ebe7f2",
    secondaryText: "#bbb4c8",
    mutedText: "#857e92",
    accent: "#9a8ec0",
    accentHover: "#aea3d0",
    accentText: "#16121f",
  },
  {
    id: "atrium-seafoam",
    name: "Seafoam",
    description: "aqua pastel light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e4f3f0",
    raisedBackground: "#f1faf8",
    primaryText: "#1f3330",
    secondaryText: "#4a625e",
    mutedText: "#768f8a",
    accent: "#2ea996",
    accentHover: "#248a7a",
    accentText: "#f1faf8",
  },
  {
    id: "atrium-lava-glass",
    name: "Lava Glass",
    description: "black and lava red",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#120a0a",
    raisedBackground: "#1e1010",
    primaryText: "#ffe4e0",
    secondaryText: "#d8b0aa",
    mutedText: "#9a7874",
    accent: "#ff4d3a",
    accentHover: "#ff6b5a",
    accentText: "#280c0a",
  },
  {
    id: "atrium-fog-harbor",
    name: "Fog Harbor",
    description: "grey-blue fog light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e6ebf0",
    raisedBackground: "#f3f6f9",
    primaryText: "#24303a",
    secondaryText: "#4d5c6a",
    mutedText: "#7a8a98",
    accent: "#5a7ea8",
    accentHover: "#486888",
    accentText: "#f3f6f9",
  },
  {
    id: "atrium-amber-vault",
    name: "Amber Vault",
    description: "treasure amber dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#1a140c",
    raisedBackground: "#261e12",
    primaryText: "#f5e8d0",
    secondaryText: "#cbb894",
    mutedText: "#92846a",
    accent: "#f0a020",
    accentHover: "#ffb43a",
    accentText: "#2a1808",
  },
  {
    id: "atrium-mint-folio",
    name: "Mint Folio",
    description: "crisp mint page",
    base: "light",
    tags: ["light","green"],
    appBackground: "#e6f4ee",
    raisedBackground: "#f3faf6",
    primaryText: "#1f322a",
    secondaryText: "#4a6156",
    mutedText: "#768e82",
    accent: "#2f9e74",
    accentHover: "#25805e",
    accentText: "#f3faf6",
  },
  {
    id: "atrium-orchid-night",
    name: "Orchid Night",
    description: "deep orchid",
    base: "dark",
    tags: ["dark","violet"],
    appBackground: "#160f1a",
    raisedBackground: "#221828",
    primaryText: "#f4e6f8",
    secondaryText: "#ceb2d6",
    mutedText: "#947c9c",
    accent: "#c45ad8",
    accentHover: "#d478e6",
    accentText: "#1e0c24",
  },
  {
    id: "atrium-clay-studio",
    name: "Clay Studio",
    description: "terracotta light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f3e8e0",
    raisedBackground: "#faf3ee",
    primaryText: "#3a2a24",
    secondaryText: "#6a5248",
    mutedText: "#967c72",
    accent: "#c26b4a",
    accentHover: "#a8583c",
    accentText: "#faf3ee",
  },
  {
    id: "atrium-steel-rain",
    name: "Steel Rain",
    description: "cold steel dark",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#121416",
    raisedBackground: "#1c1f22",
    primaryText: "#e8eaec",
    secondaryText: "#b4b8bc",
    mutedText: "#808488",
    accent: "#9aa4b0",
    accentHover: "#b0bac4",
    accentText: "#0e1012",
  },
  {
    id: "atrium-blueberry",
    name: "Blueberry",
    description: "bright berry light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e8eef8",
    raisedBackground: "#f4f7fc",
    primaryText: "#222c40",
    secondaryText: "#4c5870",
    mutedText: "#7884a0",
    accent: "#4a6fd4",
    accentHover: "#3a58b0",
    accentText: "#f4f7fc",
  },
  {
    id: "atrium-moss-temple",
    name: "Moss Temple",
    description: "ancient moss dark",
    base: "dark",
    tags: ["dark","green"],
    appBackground: "#10160e",
    raisedBackground: "#1a2216",
    primaryText: "#e4f0dc",
    secondaryText: "#b0c4a4",
    mutedText: "#7c9074",
    accent: "#6aa84a",
    accentHover: "#82c05e",
    accentText: "#0e180a",
  },
  {
    id: "atrium-champagne",
    name: "Champagne",
    description: "pale gold celebration",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f5efdf",
    raisedBackground: "#fbf7ec",
    primaryText: "#3a3220",
    secondaryText: "#655840",
    mutedText: "#90806a",
    accent: "#c4a24a",
    accentHover: "#a88838",
    accentText: "#fbf7ec",
  },
  {
    id: "atrium-eclipse",
    name: "Eclipse",
    description: "near-black cyan",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0a0e10",
    raisedBackground: "#12181c",
    primaryText: "#dceef2",
    secondaryText: "#a0c0c8",
    mutedText: "#6a8a90",
    accent: "#20d0e0",
    accentHover: "#48dce8",
    accentText: "#061418",
  },
  {
    id: "atrium-rose-quartz",
    name: "Rose Quartz",
    description: "milky rose light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f6eaee",
    raisedBackground: "#fcf5f7",
    primaryText: "#3a2830",
    secondaryText: "#68505a",
    mutedText: "#947880",
    accent: "#c87890",
    accentHover: "#b06078",
    accentText: "#fcf5f7",
  },
  {
    id: "atrium-indigo-ink",
    name: "Indigo Ink",
    description: "deep indigo page",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0e1220",
    raisedBackground: "#161c30",
    primaryText: "#e0e6ff",
    secondaryText: "#a8b4e0",
    mutedText: "#7480a8",
    accent: "#5a6cff",
    accentHover: "#7484ff",
    accentText: "#0c1028",
  },
  {
    id: "atrium-kiwi",
    name: "Kiwi",
    description: "fresh kiwi light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#eaf4e2",
    raisedBackground: "#f5faef",
    primaryText: "#28341e",
    secondaryText: "#526248",
    mutedText: "#7c8e72",
    accent: "#7cbc3a",
    accentHover: "#649c2c",
    accentText: "#f5faef",
  },
  {
    id: "atrium-obsidian",
    name: "Obsidian",
    description: "pure dark glass",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#0c0c0e",
    raisedBackground: "#161618",
    primaryText: "#f0f0f2",
    secondaryText: "#b8b8bc",
    mutedText: "#808084",
    accent: "#c8c8d0",
    accentHover: "#e0e0e8",
    accentText: "#08080a",
  },
  {
    id: "atrium-apricot",
    name: "Apricot",
    description: "sunny apricot light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f7ebe0",
    raisedBackground: "#fcf5ef",
    primaryText: "#3a2c22",
    secondaryText: "#685448",
    mutedText: "#947c70",
    accent: "#e08848",
    accentHover: "#c47038",
    accentText: "#fcf5ef",
  },
  {
    id: "atrium-twilight-bay",
    name: "Twilight Bay",
    description: "purple-blue dusk",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#12141f",
    raisedBackground: "#1c2030",
    primaryText: "#e6e8ff",
    secondaryText: "#b0b6e0",
    mutedText: "#7c84a8",
    accent: "#7a8cff",
    accentHover: "#96a4ff",
    accentText: "#101428",
  },
  {
    id: "atrium-sage-ledger",
    name: "Sage Ledger",
    description: "sage paper light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#e8eee6",
    raisedBackground: "#f4f8f2",
    primaryText: "#2a3228",
    secondaryText: "#545e50",
    mutedText: "#7e8a7a",
    accent: "#6a8f6a",
    accentHover: "#567656",
    accentText: "#f4f8f2",
  },
  {
    id: "atrium-ruby-cellar",
    name: "Ruby Cellar",
    description: "wine cellar dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#160c10",
    raisedBackground: "#22141a",
    primaryText: "#f6e4ea",
    secondaryText: "#d0aab4",
    mutedText: "#967880",
    accent: "#c43a5a",
    accentHover: "#d85872",
    accentText: "#220810",
  },
  {
    id: "atrium-cloud-linen",
    name: "Cloud Linen",
    description: "soft linen light",
    base: "light",
    tags: ["light","mono"],
    appBackground: "#efeee9",
    raisedBackground: "#f8f7f3",
    primaryText: "#2c2b28",
    secondaryText: "#585652",
    mutedText: "#84817c",
    accent: "#5a6a7a",
    accentHover: "#485868",
    accentText: "#f8f7f3",
  },
  {
    id: "atrium-plasma",
    name: "Plasma",
    description: "electric purple dark",
    base: "dark",
    tags: ["dark","neon"],
    appBackground: "#120818",
    raisedBackground: "#1e0e28",
    primaryText: "#f2e0ff",
    secondaryText: "#c8a8e0",
    mutedText: "#8e78a8",
    accent: "#c040ff",
    accentHover: "#d068ff",
    accentText: "#1a0828",
  },
  {
    id: "atrium-lemonade",
    name: "Lemonade",
    description: "bright lemon light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f6f3d8",
    raisedBackground: "#fbf9ea",
    primaryText: "#38341c",
    secondaryText: "#625c3c",
    mutedText: "#8e885e",
    accent: "#d4c028",
    accentHover: "#b8a61c",
    accentText: "#fbf9ea",
  },
  {
    id: "atrium-harbor-night",
    name: "Harbor Night",
    description: "navy dock dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0e1620",
    raisedBackground: "#162230",
    primaryText: "#e0ecf4",
    secondaryText: "#a8bcc8",
    mutedText: "#748890",
    accent: "#3a9ad4",
    accentHover: "#58b0e4",
    accentText: "#0a1824",
  },
  {
    id: "atrium-petal",
    name: "Petal",
    description: "delicate petal pink",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f7ecef",
    raisedBackground: "#fcf5f7",
    primaryText: "#382830",
    secondaryText: "#645058",
    mutedText: "#907880",
    accent: "#e08aa4",
    accentHover: "#c8728c",
    accentText: "#fcf5f7",
  },
  {
    id: "atrium-bronze",
    name: "Bronze",
    description: "aged bronze dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#16120e",
    raisedBackground: "#221c16",
    primaryText: "#f0e4d4",
    secondaryText: "#c8b49c",
    mutedText: "#908070",
    accent: "#c89448",
    accentHover: "#d8a860",
    accentText: "#1e140a",
  },
  {
    id: "atrium-skyline",
    name: "Skyline",
    description: "clear sky light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e6f0f8",
    raisedBackground: "#f2f7fb",
    primaryText: "#1e2c38",
    secondaryText: "#4a5c6c",
    mutedText: "#768a9a",
    accent: "#3a8ad4",
    accentHover: "#2e70b0",
    accentText: "#f2f7fb",
  },
  {
    id: "atrium-shadow-fern",
    name: "Shadow Fern",
    description: "deep fern dark",
    base: "dark",
    tags: ["dark","green"],
    appBackground: "#0e140e",
    raisedBackground: "#182018",
    primaryText: "#e0f0e0",
    secondaryText: "#a8c4a8",
    mutedText: "#748e74",
    accent: "#48a858",
    accentHover: "#64c070",
    accentText: "#0a180a",
  },
  {
    id: "atrium-porcelain",
    name: "Porcelain",
    description: "cool porcelain light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#eceef2",
    raisedBackground: "#f6f7fa",
    primaryText: "#262830",
    secondaryText: "#525460",
    mutedText: "#7e808c",
    accent: "#6a7a9a",
    accentHover: "#586480",
    accentText: "#f6f7fa",
  },
  {
    id: "atrium-magma",
    name: "Magma",
    description: "volcanic orange dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#160c08",
    raisedBackground: "#24140c",
    primaryText: "#ffe6d4",
    secondaryText: "#d8b098",
    mutedText: "#987868",
    accent: "#ff6a20",
    accentHover: "#ff8848",
    accentText: "#280e06",
  },
  {
    id: "atrium-wisteria",
    name: "Wisteria",
    description: "soft purple light",
    base: "light",
    tags: ["light","violet"],
    appBackground: "#efe8f4",
    raisedBackground: "#f7f2fa",
    primaryText: "#2e2438",
    secondaryText: "#5a4c68",
    mutedText: "#867894",
    accent: "#9870c4",
    accentHover: "#8058ac",
    accentText: "#f7f2fa",
  },
  {
    id: "atrium-carbon",
    name: "Carbon",
    description: "matte carbon dark",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#101010",
    raisedBackground: "#1a1a1a",
    primaryText: "#ececec",
    secondaryText: "#b4b4b4",
    mutedText: "#808080",
    accent: "#ff6b35",
    accentHover: "#ff8558",
    accentText: "#140c08",
  },
  {
    id: "atrium-meadow",
    name: "Meadow",
    description: "open meadow light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#eaf1e4",
    raisedBackground: "#f5f9f0",
    primaryText: "#283222",
    secondaryText: "#525e48",
    mutedText: "#7c8a70",
    accent: "#5a9a48",
    accentHover: "#487e3a",
    accentText: "#f5f9f0",
  },
  {
    id: "atrium-sapphire",
    name: "Sapphire",
    description: "royal sapphire dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0c1220",
    raisedBackground: "#141c32",
    primaryText: "#dde6ff",
    secondaryText: "#a8b8e8",
    mutedText: "#7484b0",
    accent: "#2f6bff",
    accentHover: "#5288ff",
    accentText: "#0a1028",
  },
  {
    id: "atrium-sandstone",
    name: "Sandstone",
    description: "desert stone light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f1e9dc",
    raisedBackground: "#f8f3ea",
    primaryText: "#362e22",
    secondaryText: "#625648",
    mutedText: "#8e8272",
    accent: "#b88850",
    accentHover: "#9a7040",
    accentText: "#f8f3ea",
  },
  {
    id: "atrium-mirage",
    name: "Mirage",
    description: "purple desert dark",
    base: "dark",
    tags: ["dark","violet"],
    appBackground: "#16101a",
    raisedBackground: "#221828",
    primaryText: "#f0e4f4",
    secondaryText: "#c8b0d0",
    mutedText: "#8e7a96",
    accent: "#d070d8",
    accentHover: "#e090e8",
    accentText: "#1e0e24",
  },
  {
    id: "atrium-frost",
    name: "Frost",
    description: "winter frost light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e8f0f4",
    raisedBackground: "#f4f8fa",
    primaryText: "#223038",
    secondaryText: "#4e5e68",
    mutedText: "#7a8a94",
    accent: "#4a9ab8",
    accentHover: "#3a7e98",
    accentText: "#f4f8fa",
  },
  {
    id: "atrium-cinder",
    name: "Cinder",
    description: "ash and ember dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#14100e",
    raisedBackground: "#1e1814",
    primaryText: "#eee4da",
    secondaryText: "#c4b4a4",
    mutedText: "#8a7c70",
    accent: "#e07040",
    accentHover: "#f08858",
    accentText: "#221008",
  },
  {
    id: "atrium-jade",
    name: "Jade",
    description: "polished jade light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#e4f0ea",
    raisedBackground: "#f0f8f4",
    primaryText: "#22342c",
    secondaryText: "#4e6458",
    mutedText: "#7a9084",
    accent: "#2e9a74",
    accentHover: "#247e5e",
    accentText: "#f0f8f4",
  },
  {
    id: "atrium-velvet",
    name: "Velvet",
    description: "velvet red dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#160a0e",
    raisedBackground: "#241018",
    primaryText: "#f8e4ea",
    secondaryText: "#d4aab8",
    mutedText: "#987888",
    accent: "#c83058",
    accentHover: "#e04870",
    accentText: "#220810",
  },
  {
    id: "atrium-pearl",
    name: "Pearl",
    description: "pearlescent light",
    base: "light",
    tags: ["light","mono"],
    appBackground: "#efeeea",
    raisedBackground: "#f8f7f4",
    primaryText: "#2c2a28",
    secondaryText: "#585450",
    mutedText: "#84807c",
    accent: "#8a7a6a",
    accentHover: "#726458",
    accentText: "#f8f7f4",
  },
  {
    id: "atrium-aurora",
    name: "Aurora",
    description: "northern lights dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0c1418",
    raisedBackground: "#142028",
    primaryText: "#e0f4f0",
    secondaryText: "#a8d0c8",
    mutedText: "#749890",
    accent: "#40d8b0",
    accentHover: "#60e8c4",
    accentText: "#081820",
  },
  {
    id: "atrium-tangerine",
    name: "Tangerine",
    description: "bright citrus light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f7ebe0",
    raisedBackground: "#fcf5ef",
    primaryText: "#3a2a1e",
    secondaryText: "#68503e",
    mutedText: "#94766a",
    accent: "#f07828",
    accentHover: "#d06018",
    accentText: "#fcf5ef",
  },
  {
    id: "atrium-inkwell",
    name: "Inkwell",
    description: "classic ink dark",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#0e1014",
    raisedBackground: "#181c22",
    primaryText: "#e8ecf0",
    secondaryText: "#b0b8c0",
    mutedText: "#7a848c",
    accent: "#4a90d8",
    accentHover: "#68a8e8",
    accentText: "#0a121c",
  },
  {
    id: "atrium-blossom",
    name: "Blossom",
    description: "spring blossom light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f6ecf0",
    raisedBackground: "#fcf5f8",
    primaryText: "#382830",
    secondaryText: "#645058",
    mutedText: "#907880",
    accent: "#e07098",
    accentHover: "#c85880",
    accentText: "#fcf5f8",
  },
  {
    id: "atrium-thunder",
    name: "Thunder",
    description: "storm grey dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#12161a",
    raisedBackground: "#1c2228",
    primaryText: "#e4eaf0",
    secondaryText: "#aeb6c0",
    mutedText: "#7a8490",
    accent: "#6a90c8",
    accentHover: "#88a8d8",
    accentText: "#0e141c",
  },
  {
    id: "atrium-olive",
    name: "Olive",
    description: "muted olive light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#ece9dc",
    raisedBackground: "#f6f4ea",
    primaryText: "#302e20",
    secondaryText: "#5a5640",
    mutedText: "#86805e",
    accent: "#7a8a40",
    accentHover: "#647234",
    accentText: "#f6f4ea",
  },
  {
    id: "atrium-neon-lime",
    name: "Neon Lime",
    description: "acid lime dark",
    base: "dark",
    tags: ["dark","neon"],
    appBackground: "#0c1208",
    raisedBackground: "#161e10",
    primaryText: "#e8f8d8",
    secondaryText: "#b0d498",
    mutedText: "#7a9c6a",
    accent: "#b8ff20",
    accentHover: "#ccff58",
    accentText: "#101808",
  },
  {
    id: "atrium-dusty-rose",
    name: "Dusty Rose",
    description: "muted rose light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f2e8e8",
    raisedBackground: "#f9f3f3",
    primaryText: "#362828",
    secondaryText: "#625050",
    mutedText: "#8e7878",
    accent: "#b87878",
    accentHover: "#9c6060",
    accentText: "#f9f3f3",
  },
  {
    id: "atrium-abyss",
    name: "Abyss",
    description: "deep ocean abyss",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#060c14",
    raisedBackground: "#0e1824",
    primaryText: "#d8e8f4",
    secondaryText: "#98b4c8",
    mutedText: "#648090",
    accent: "#2080c0",
    accentHover: "#4098d8",
    accentText: "#061420",
  },
  {
    id: "atrium-marigold",
    name: "Marigold",
    description: "golden flower light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f6edd8",
    raisedBackground: "#fbf6ea",
    primaryText: "#3a3018",
    secondaryText: "#665840",
    mutedText: "#928060",
    accent: "#e0a020",
    accentHover: "#c08818",
    accentText: "#fbf6ea",
  },
  {
    id: "atrium-amethyst",
    name: "Amethyst",
    description: "crystal purple dark",
    base: "dark",
    tags: ["dark","violet"],
    appBackground: "#120e1a",
    raisedBackground: "#1e1830",
    primaryText: "#ece0f8",
    secondaryText: "#c0b0d8",
    mutedText: "#8878a0",
    accent: "#9858e0",
    accentHover: "#b078f0",
    accentText: "#160e28",
  },
  {
    id: "atrium-seafoam-dark",
    name: "Seafoam Dark",
    description: "deep seafoam",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0c1816",
    raisedBackground: "#142420",
    primaryText: "#dcf0ea",
    secondaryText: "#a0c8bc",
    mutedText: "#6c9488",
    accent: "#30c0a0",
    accentHover: "#50d4b4",
    accentText: "#081816",
  },
  {
    id: "atrium-chalk",
    name: "Chalk",
    description: "classroom chalk light",
    base: "light",
    tags: ["light","mono"],
    appBackground: "#eef0ea",
    raisedBackground: "#f7f8f4",
    primaryText: "#2a2c28",
    secondaryText: "#545650",
    mutedText: "#7e8078",
    accent: "#4a6a8a",
    accentHover: "#3a5670",
    accentText: "#f7f8f4",
  },
  {
    id: "atrium-ember-ash",
    name: "Ember Ash",
    description: "cool ash with ember",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#141210",
    raisedBackground: "#1e1c18",
    primaryText: "#ece6de",
    secondaryText: "#c0b8ac",
    mutedText: "#888078",
    accent: "#e85030",
    accentHover: "#f07050",
    accentText: "#1c0c08",
  },
  {
    id: "atrium-iris",
    name: "Iris",
    description: "iris blue light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e8eaf4",
    raisedBackground: "#f4f5fa",
    primaryText: "#262838",
    secondaryText: "#505468",
    mutedText: "#7a8094",
    accent: "#6870c8",
    accentHover: "#5458b0",
    accentText: "#f4f5fa",
  },
  {
    id: "atrium-mahogany",
    name: "Mahogany",
    description: "rich wood dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#160e0c",
    raisedBackground: "#221612",
    primaryText: "#f0e0d6",
    secondaryText: "#c8b0a4",
    mutedText: "#907c72",
    accent: "#b05030",
    accentHover: "#c86848",
    accentText: "#1e0c08",
  },
  {
    id: "atrium-celery",
    name: "Celery",
    description: "pale celery light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#eef2e4",
    raisedBackground: "#f6f8f0",
    primaryText: "#2c3220",
    secondaryText: "#565e40",
    mutedText: "#808a60",
    accent: "#8aaa40",
    accentHover: "#728e34",
    accentText: "#f6f8f0",
  },
  {
    id: "atrium-ultraviolet",
    name: "Ultraviolet",
    description: "UV glow dark",
    base: "dark",
    tags: ["dark","neon"],
    appBackground: "#0e0818",
    raisedBackground: "#1a1028",
    primaryText: "#ece0ff",
    secondaryText: "#c0a8e8",
    mutedText: "#8878b0",
    accent: "#8a20ff",
    accentHover: "#a850ff",
    accentText: "#140820",
  },
  {
    id: "atrium-biscuit",
    name: "Biscuit",
    description: "warm biscuit light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f3eadc",
    raisedBackground: "#f9f4ec",
    primaryText: "#362c20",
    secondaryText: "#625440",
    mutedText: "#8e7c68",
    accent: "#c09050",
    accentHover: "#a47840",
    accentText: "#f9f4ec",
  },
  {
    id: "atrium-mercury",
    name: "Mercury",
    description: "liquid metal dark",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#121416",
    raisedBackground: "#1c1e22",
    primaryText: "#e8eaee",
    secondaryText: "#b4b8c0",
    mutedText: "#80848c",
    accent: "#a0a8b8",
    accentHover: "#b8c0d0",
    accentText: "#0c0e12",
  },
  {
    id: "atrium-coral-reef",
    name: "Coral Reef",
    description: "reef pastel light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f6eae6",
    raisedBackground: "#fcf5f2",
    primaryText: "#3a2824",
    secondaryText: "#68504a",
    mutedText: "#947872",
    accent: "#e07860",
    accentHover: "#c4604a",
    accentText: "#fcf5f2",
  },
  {
    id: "atrium-night-owl",
    name: "Night Owl",
    description: "late study dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0e1218",
    raisedBackground: "#181e28",
    primaryText: "#e4eaf2",
    secondaryText: "#aeb8c8",
    mutedText: "#7a8494",
    accent: "#4a9cff",
    accentHover: "#6ab0ff",
    accentText: "#0a121e",
  },
  {
    id: "atrium-pistachio",
    name: "Pistachio",
    description: "soft pistachio light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#eaf0e4",
    raisedBackground: "#f5f8f0",
    primaryText: "#2a3224",
    secondaryText: "#545e48",
    mutedText: "#7e8a6c",
    accent: "#7aa858",
    accentHover: "#648c48",
    accentText: "#f5f8f0",
  },
  {
    id: "atrium-garnet",
    name: "Garnet",
    description: "deep garnet dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#160a0c",
    raisedBackground: "#221214",
    primaryText: "#f4e0e4",
    secondaryText: "#d0a8b0",
    mutedText: "#947880",
    accent: "#b02840",
    accentHover: "#c84860",
    accentText: "#1e080c",
  },
  {
    id: "atrium-linen-blue",
    name: "Linen Blue",
    description: "blue linen light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e8ecf2",
    raisedBackground: "#f4f6f9",
    primaryText: "#262c38",
    secondaryText: "#505868",
    mutedText: "#7a8494",
    accent: "#5a7ab0",
    accentHover: "#486498",
    accentText: "#f4f6f9",
  },
  {
    id: "atrium-smog",
    name: "Smog",
    description: "urban smog dark",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#141210",
    raisedBackground: "#1e1c18",
    primaryText: "#e8e4de",
    secondaryText: "#b8b4ac",
    mutedText: "#848078",
    accent: "#d09040",
    accentHover: "#e0a858",
    accentText: "#1a1008",
  },
  {
    id: "atrium-hibiscus",
    name: "Hibiscus",
    description: "tropical flower light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f6e8ec",
    raisedBackground: "#fcf3f6",
    primaryText: "#3a2430",
    secondaryText: "#684c58",
    mutedText: "#947480",
    accent: "#d05080",
    accentHover: "#b8406c",
    accentText: "#fcf3f6",
  },
  {
    id: "atrium-deep-teal",
    name: "Deep Teal",
    description: "museum teal dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0c1616",
    raisedBackground: "#142222",
    primaryText: "#dceeea",
    secondaryText: "#a0c4bc",
    mutedText: "#6c9088",
    accent: "#28a898",
    accentHover: "#40c0ae",
    accentText: "#081816",
  },
  {
    id: "atrium-vanilla",
    name: "Vanilla",
    description: "vanilla cream light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f5f0e4",
    raisedBackground: "#faf7f0",
    primaryText: "#363022",
    secondaryText: "#625a42",
    mutedText: "#8e8668",
    accent: "#c4a860",
    accentHover: "#a89048",
    accentText: "#faf7f0",
  },
  {
    id: "atrium-punch",
    name: "Punch",
    description: "fruit punch dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#160c10",
    raisedBackground: "#24141a",
    primaryText: "#f8e4ea",
    secondaryText: "#d4aab4",
    mutedText: "#987888",
    accent: "#ff4070",
    accentHover: "#ff6890",
    accentText: "#220810",
  },
  {
    id: "atrium-sky-wash",
    name: "Sky Wash",
    description: "washed sky light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e6f0f6",
    raisedBackground: "#f2f7fa",
    primaryText: "#223038",
    secondaryText: "#4e5e68",
    mutedText: "#7a8a94",
    accent: "#4a9ec8",
    accentHover: "#3a82a8",
    accentText: "#f2f7fa",
  },
  {
    id: "atrium-basalt",
    name: "Basalt",
    description: "volcanic rock dark",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#101010",
    raisedBackground: "#1a1a1a",
    primaryText: "#e8e8e8",
    secondaryText: "#b0b0b0",
    mutedText: "#7c7c7c",
    accent: "#ff9040",
    accentHover: "#ffa868",
    accentText: "#141008",
  },
  {
    id: "atrium-fern-light",
    name: "Fern Light",
    description: "sunlit fern",
    base: "light",
    tags: ["light","green"],
    appBackground: "#e8f0e4",
    raisedBackground: "#f4f8f0",
    primaryText: "#283222",
    secondaryText: "#525e48",
    mutedText: "#7c8a70",
    accent: "#4a9a50",
    accentHover: "#3a8040",
    accentText: "#f4f8f0",
  },
  {
    id: "atrium-orchid-light",
    name: "Orchid Light",
    description: "pale orchid day",
    base: "light",
    tags: ["light","violet"],
    appBackground: "#f0e8f2",
    raisedBackground: "#f8f3f9",
    primaryText: "#302438",
    secondaryText: "#5a4c68",
    mutedText: "#867894",
    accent: "#a870c0",
    accentHover: "#9058a8",
    accentText: "#f8f3f9",
  },
  {
    id: "atrium-coal",
    name: "Coal",
    description: "coal black orange",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#0c0c0c",
    raisedBackground: "#161616",
    primaryText: "#f0e8e0",
    secondaryText: "#c0b4a8",
    mutedText: "#887c70",
    accent: "#ff7020",
    accentHover: "#ff8c48",
    accentText: "#180c04",
  },
  {
    id: "atrium-breeze",
    name: "Breeze",
    description: "airy cool light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e8f2f4",
    raisedBackground: "#f4f9fa",
    primaryText: "#223438",
    secondaryText: "#4e6268",
    mutedText: "#7a8e94",
    accent: "#3a9aa8",
    accentHover: "#2e808c",
    accentText: "#f4f9fa",
  },
  {
    id: "atrium-mulberry",
    name: "Mulberry",
    description: "mulberry night",
    base: "dark",
    tags: ["dark","violet"],
    appBackground: "#140c14",
    raisedBackground: "#201420",
    primaryText: "#f0e4f0",
    secondaryText: "#c8b0c8",
    mutedText: "#8e7a8e",
    accent: "#b040a0",
    accentHover: "#c860b8",
    accentText: "#1c0818",
  },
  {
    id: "atrium-wheat",
    name: "Wheat",
    description: "golden wheat light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f3ecd8",
    raisedBackground: "#f9f5ea",
    primaryText: "#38301c",
    secondaryText: "#645840",
    mutedText: "#908060",
    accent: "#c4a040",
    accentHover: "#a88830",
    accentText: "#f9f5ea",
  },
  {
    id: "atrium-cypress",
    name: "Cypress",
    description: "mediterranean dark",
    base: "dark",
    tags: ["dark","green"],
    appBackground: "#0e1410",
    raisedBackground: "#182018",
    primaryText: "#e0ece0",
    secondaryText: "#a8c0a8",
    mutedText: "#748c74",
    accent: "#509060",
    accentHover: "#68a878",
    accentText: "#0c180e",
  },
  {
    id: "atrium-cotton",
    name: "Cotton",
    description: "soft cotton light",
    base: "light",
    tags: ["light","mono"],
    appBackground: "#efefeb",
    raisedBackground: "#f8f8f5",
    primaryText: "#2c2c2a",
    secondaryText: "#585854",
    mutedText: "#848480",
    accent: "#6a8aaa",
    accentHover: "#567090",
    accentText: "#f8f8f5",
  },
  {
    id: "atrium-flare",
    name: "Flare",
    description: "solar flare dark",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#160e08",
    raisedBackground: "#24180e",
    primaryText: "#ffe8d4",
    secondaryText: "#d8b898",
    mutedText: "#98806a",
    accent: "#ff9020",
    accentHover: "#ffaa48",
    accentText: "#241008",
  },
  {
    id: "atrium-lagoon",
    name: "Lagoon",
    description: "tropical lagoon light",
    base: "light",
    tags: ["light","cool"],
    appBackground: "#e4f2f0",
    raisedBackground: "#f0f9f7",
    primaryText: "#1e3330",
    secondaryText: "#4a605c",
    mutedText: "#768e8a",
    accent: "#2aa898",
    accentHover: "#228a7c",
    accentText: "#f0f9f7",
  },
  {
    id: "atrium-noir",
    name: "Noir",
    description: "cinema noir dark",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#0a0a0a",
    raisedBackground: "#141414",
    primaryText: "#f0f0f0",
    secondaryText: "#b8b8b8",
    mutedText: "#808080",
    accent: "#e0b040",
    accentHover: "#f0c860",
    accentText: "#140e04",
  },
  {
    id: "atrium-blossom-dark",
    name: "Blossom Dark",
    description: "night blossom",
    base: "dark",
    tags: ["dark","warm"],
    appBackground: "#140e12",
    raisedBackground: "#201820",
    primaryText: "#f4e4ec",
    secondaryText: "#d0b0c0",
    mutedText: "#947888",
    accent: "#e06090",
    accentHover: "#f080a8",
    accentText: "#1c0a14",
  },
  {
    id: "atrium-glen",
    name: "Glen",
    description: "scottish glen light",
    base: "light",
    tags: ["light","green"],
    appBackground: "#e8eee4",
    raisedBackground: "#f4f7f0",
    primaryText: "#283022",
    secondaryText: "#525c48",
    mutedText: "#7c8670",
    accent: "#5a8a58",
    accentHover: "#487248",
    accentText: "#f4f7f0",
  },
  {
    id: "atrium-comet",
    name: "Comet",
    description: "comet trail dark",
    base: "dark",
    tags: ["dark","cool"],
    appBackground: "#0c1018",
    raisedBackground: "#161c28",
    primaryText: "#e0e8f4",
    secondaryText: "#a8b8d0",
    mutedText: "#7484a0",
    accent: "#60a0ff",
    accentHover: "#80b8ff",
    accentText: "#0a1220",
  },
  {
    id: "atrium-nectar",
    name: "Nectar",
    description: "honey nectar light",
    base: "light",
    tags: ["light","warm"],
    appBackground: "#f5ecd8",
    raisedBackground: "#faf5ea",
    primaryText: "#3a3018",
    secondaryText: "#665840",
    mutedText: "#928060",
    accent: "#d4a028",
    accentHover: "#b8881c",
    accentText: "#faf5ea",
  },
  {
    id: "atrium-onyx",
    name: "Onyx",
    description: "polished onyx dark",
    base: "dark",
    tags: ["dark","mono"],
    appBackground: "#080808",
    raisedBackground: "#121212",
    primaryText: "#ececec",
    secondaryText: "#b4b4b4",
    mutedText: "#7c7c7c",
    accent: "#50c8ff",
    accentHover: "#78d8ff",
    accentText: "#061018",
  },
];

export const catalogThemes: ThemeDocument[] = paletteCatalog.map(fromPalette);

export const builtinThemes: ThemeDocument[] = [
  mistTheme,
  duskTheme,
  ...catalogThemes,
];

export function getThemeById(id: string): ThemeDocument | undefined {
  return builtinThemes.find((theme) => theme.id === id);
}
